name: CI workflow
on:
push:
jobs:
  build:
    runs-on: ubuntu-latest #github-hosted runner(free)
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/checkout@v4

        namee: set up docker
        uses: docker/setup-buildx-action@v4
       